{% set name = "qgis" %}
{% set version = "3.4.4" %}

package:
  name: qgis
  version: {{ version }}

source:
  url: https://qgis.org/downloads/{{ name }}-{{ version }}.tar.bz2
  sha256: f47d2bf714f4397b272ab6bad874dcbb5fc305cdfcc78a04e8e0c3255d67bcda
  patches:
    # QGIS inserts Qt plugin locations into PATH relative to build location
    # This patch fixes it so PATH is relative to install location
    # FIXME: fails to patch under 3.4.4
    - 0001_plugins_path.patch  # [linux]
    # By default looks for pyrcc5.bat on Windows, but we have pyrcc5.exe
    - 0002_pyrcc.patch  # [win]
    # Dets the wrong geos lib
    - 0004_geoscmake.patch  # [win]
    # Don't try and install MSVC runtime libs as they already exist
    - 0005_CMakeLists.nosyslibs.patch  # [win]
    # Ensure GRASS plugin's shell uses python2.exe
    - 0006_set_grass_python2.patch  # [win]
    # See: https://github.com/conda-forge/gdal-feedstock/issues/25
    - 0007_mdal_provider_hdf5_dll.patch  # [win]
    # Temp fixes for 3.4.4 and /vzip/ gdal/ogr paths (remove on pushed PRs)
    - 0008_temp_processing_vzip_fixes.patch

build:
  number: 1012
  skip: true  # [py2k]
  script_env:
    # For just running CMake config during 'conda build'; set =1
    - CONFIGONLY
    # See: README-customize
    - QGIS_PRE_CUSTOMIZE_DIR
    - QGIS_POST_CUSTOMIZE_DIR

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - m2-flex  # [win]
    - m2-bison  # [win]
    - m2-m4  # [win]
    - m2-patch  # [win]
    - m2-sed  # [win]
  host:
    - python >=3.6
    - flex  # [unix]
    - bison  # [unix]
    - m4  # [unix]
    - sip
    - expat
    - icu
    - libiconv
    - libzip
    - libtasn1  # [osx]
    # Qt stack
    - qt 5.9.*
    - pyqt 5.9.*
    - qtwebkit 5.9.*
    - qscintilla2
    - qca
    - qwt
    - qwtpolar
    - qtkeychain
    # GDAL stack
    - gdal >=2.4
    - geos
    - proj4
    # GSL for georeferencer
    - gsl
    - sqlite
    - libspatialindex
    - libspatialite
    - libpq
    - oracle-oci-libs
    # osgeo-forge and osgeo4w build support
    - win-utils  # [win]
    # - menuinst  # [win]
    - osgf-env
    # C++ plugin support
    - grass 7.*
    # Python pkgs
    - six
    # Python pkgs to launch QGIS when debugging during conda build
    - owslib
    - psycopg2
    # Just to ensure older 'defaults' one is not used
    - numpy >=1.15

  run:
    - python >=3.6
    - expat
    - icu
    - libiconv
    - libzip
    - libtasn1  # [osx]
    - qt 5.9.*
    - pyqt 5.9.*
    - qtwebkit 5.9.*
    - pyqtwebkit 5.9.*
    - qscintilla2
    - qca
    - qwt
    - qwtpolar
    - qtkeychain
    - gdal >=2.4
    - geos
    - proj4
    - gsl
    - sqlite
    - libspatialindex
    - libspatialite
    - libpq
    - oracle-oci-libs
    # C++ plugin support
    - grass 7.*
    - gpsbabel
    # osgeo-forge and osgeo4w support
    - win-utils  # [win]
    - osgf-env
    # - menuinst  # [win]
    # Runtime Python library deps
    - future
    - httplib2
    - jinja2
    - markupsafe
    - mock
    - nose2
    - numpy >=1.15
    - owslib
    - plotly
    - psycopg2
    - pygments
    - pyproj
    - python-dateutil
    - pytz
    - pyyaml
    - requests
    - six
    - sip
    - yaml

test:
  commands:
    # cannot execute this at the moment:
    # raise ImportError('This package should not be accessible on Python 3.
    # - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://qgis.org/
  license: GPL-2.0
  license_file: COPYING
  summary: 'A free and open source Geographic Information System (GIS).'
  description: |
    QGIS is a user friendly Open Source Geographic Information System (GIS)
    licensed under the GNU General Public License. QGIS is an official
    project of the Open Source Geospatial Foundation (OSGeo). It runs on
    Linux, Unix, Mac OSX, Windows and Android and supports numerous vector,
    raster, and database formats and functionalities.
  doc_url: https://www.qgis.org/en/docs/index.html
  dev_url: https://github.com/qgis/QGIS

extra:
  recipe-maintainers:
    - ceholden
    - ocefpaf
    - dakcarto
